### ISSUE TITLE
No Issue but thank you!

### ISSUE THREAD

**Issue by boerkey** [mojoblanco/domainos#2]
This was exactly what i was looking for! Thank you very much for sharing this easy&useful codes with us.

I also have a question, If i only let one website as allowed, all other websites except allowed one wont be accepteed?

**Comment by mojoblanco** [comment]
Thanks for the comment. 

For your question, if you add one website to your whitelist, and you use `domainos:allow` , only that website will be allowed. Same if you add to whitelist and use `domainos:block`

**Comment by boerkey** [comment]
Wow its perfect John, I was looking for this kind of things. So im very
glad about it, it works I tried it. Thank you again and again :)

2018-02-13 23:39 GMT+03:00 John Olawale <notifications@github.com>:

**Comment by mojoblanco** [comment]
Glad I was able to help.
